Indentation is now a tab, and not four spaces. Keep it that way.

diff --git a/iwizxp/trunk/db/script/unloadModules b/iwizxp/trunk/db/script/unloadModules
--- a/iwizxp/trunk/db/script/unloadModules
+++ b/iwizxp/trunk/db/script/unloadModules
@@ -4,16 +4,16 @@
 # Relies on $modules.
 ##
 unloadModules() {
-    setupModules
+	setupModules
 
-    if [ -n $modules ]; then
-        for module in $modules; do
-            echo -n "Unloading $module... "
-            $rmmod $module
-            if [ $? -ne 0 ]; then
-                echo "Failure."
-            fi
-            echo "Done."
-        done
-    fi
+	if [ -n $modules ]; then
+		for module in $modules; do
+			echo -n "Unloading $module... "
+			$rmmod $module
+			if [ $? -ne 0 ]; then
+				echo "Failure."
+			fi
+			echo "Done."
+		done
+	fi
 }
